Controllers/CalendarController.cs
using NamekWebPes.Dao;
using NamekWebPes.Database.EF;
using NamekWebPes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NamekWebPes.Controllers
{
    public class CalendarController : Controller
    {
        // GET: Calendar
        FootballTournamentEntities db = new FootballTournamentEntities();
        public ActionResult Index()
        {
            var calenders = db.Calendars.ToList();
            var calenderModel = new List<CalendarModel>();
        
            foreach (var item in calenders)
            {
                var foo = new CalendarModel()
                {
                    CalendarID = item.CalendarID,
                    TenTranDau = item.TenTranDau,
                    VongDau = item.VongDau
                };
                foo.Membername1 = db.Members.Where(x => x.MemberID == item.NguoiChoi1).FirstOrDefault().Membername;
                foo.Membername2 = db.Members.Where(x => x.MemberID == item.NguoiChoi2).FirstOrDefault().Membername;
                calenderModel.Add(foo);
            }
            return View(calenderModel);
        }









        //public JsonResult ID2(int membername)
        //{
        //    List<Calendar> calendars = db.Calendars.Where(m => m.NguoiChoi2 == membername).ToList();
        //    List<CalendarModel> calendarModels = new List<CalendarModel>();

        //    foreach (var item in calendars)
        //    {
        //        var foo = db.Members.Where(x => x.MemberID == item.NguoiChoi2).First();
        //        calendarModels.Add(new CalendarModel() { Membername = foo.Membername });

        //    }
        //    return Json(calendarModels, JsonRequestBehavior.AllowGet);
        //}
    }
}

Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NamekWebPes.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult New1()
        {
            return View();
        }
        public ActionResult New2()
        {
            return View();
        }
        public ActionResult New3()
        {
            return View();
        }
    }
}

Controllers/RankController.cs
using NamekWebPes.Dao;
using NamekWebPes.Database.EF;
using NamekWebPes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NamekWebPes.Controllers
{
    public class RankController : Controller
    {
        FootballTournamentEntities db = new FootballTournamentEntities();
        // GET: Rank
      
        public ActionResult Index()
        {
            var rankdb = db.Results.GroupBy(
                ac => new {
                    ac.MemberID
                }).Select(
                ac => new ResultModel() { 
                    Logo=db.Members.Where(x=>x.MemberID==ac.Key.MemberID).FirstOrDefault().Logo,
                    MemberID = ac.Key.MemberID,
                    Goal = ac.Sum(acs => acs.Goal),
                    Lost = ac.Sum(acs => acs.Lost),
                    Redcard = ac.Sum(acs => acs.Redcard),
                    Yellowcard = ac.Sum(acs => acs.Yellowcard),
                    Point = ac.Sum(acs => acs.Point),
                    win = ac.Count(acs => acs.Point == 3),
                    blost = ac.Count(acs => acs.Point == 0),
                    hoa=ac.Count(acs=>acs.Point==1),
                    Membername= db.Members.Where(x => x.MemberID == ac.Key.MemberID).FirstOrDefault().Membername
        }).ToList();
           
            return View(rankdb);
        }
    }
}

Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NamekWebPes.Controllers
{
    public class TeamController : Controller
    {
        // GET: Team
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vie">
<head>
    <title>Giải PES Namek Mở Rộng</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="/Assets/Client/fonts/icomoon/style.css">

    <link rel="stylesheet" href="/Assets/Client/css/bootstrap.min.css">
    <link rel="stylesheet" href="/Assets/Client/css/magnific-popup.css">
    <link rel="stylesheet" href="/Assets/Client/css/jquery-ui.css">
    <link rel="stylesheet" href="/Assets/Client/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/Assets/Client/css/owl.theme.default.min.css">


    <link rel="stylesheet" href="/Assets/Client/css/aos.css">

    <link rel="stylesheet" href="/Assets/Client/css/style.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.js"></script>

</head>
<body>

    <div class="site-wrap">

        <div class="site-mobile-menu">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-logo">
                    <a href="#"><img src="/Assets/Client/images/logo.png" alt="Image"></a>
                </div>
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>

        <header class="site-navbar absolute transparent" role="banner">
            <div class="py-3">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-6 col-md-3">
                            <a href="#" class="text-secondary px-2 pl-0"><span class="icon-facebook"></span></a>
                            <a href="#" class="text-secondary px-2"><span class="icon-instagram"></span></a>
                            <a href="#" class="text-secondary px-2"><span class="icon-twitter"></span></a>
                            <a href="#" class="text-secondary px-2"><span class="icon-linkedin"></span></a>
                        </div>
                        <div class="col-6 col-md-9 text-right">
                            <div class="d-inline-block"><a href="#" class="text-secondary p-2 d-flex align-items-center"><span class="icon-envelope mr-3"></span> <span class="d-none d-md-block">namek.com.vn</span></a></div>
                            <div class="d-inline-block"><a href="tel:0978332833" class="text-secondary p-2 d-flex align-items-center"><span class="icon-phone mr-0 mr-md-3"></span> <span class="d-none d-md-block">0978332833</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <nav class="site-navigation position-relative text-right bg-black text-md-right" role="navigation">
                <div class="container position-relative">
                    <div class="site-logo">
                        <a href="@Url.Action("Index","Home")"><img src="/Assets/Client/images/logo.png" alt=""></a>
                    </div>

                    <div class="d-inline-block d-md-none ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle text-white"><span class="icon-menu h3"></span></a></div>

                    <ul class="site-menu js-clone-nav d-none d-md-block">
                        <li class=" active">
                            <a href="@Url.Action("Index","Home")">Home</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Rank")">Bảng Xếp Hạng</a>
                        </li>
                        <li><a href="@Url.Action("Index","Calendar")">Lịch Thi Đấu</a></li>
                        <li><a href="@Url.Action("Index","Team")">Team</a></li>
                        <li><a href="@Url.Action("Index","News")">Tin tức</a></li>
                        <li><a href="@Url.Action("Index", "Home", new { area = "Admin" })">Đăng Nhập</a></li>
                    </ul>
                </div>
            </nav>
        </header>



        @RenderBody()


        <footer class="site-footer border-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="mb-5">
                            <h3 class="footer-heading mb-4">Sứ mệnh chúng tôi</h3>
                            <p>Sứ mệnh của chúng tôi là trở thành một công ty kinh doanh những dịch vụ phục vụ cho ngành CNTT hàng đầu Việt Nam. Phục vụ tốt nhất những khách hàng trong thị trường mà công ty có được.</p>
                        </div>

                    </div>
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="row mb-5">
                            <div class="col-md-12">
                                <h3 class="footer-heading mb-4">Liên kết</h3>
                            </div>
                            <div class="col-md-12 col-lg-12">
                                <ul class="list-unstyled">
                                    <li><a href="bangxephang.html">Bảng xếp hạng</a></li>
                                    <li><a href="lichthidau.html">Lịch thi đấu</a></li>
                                    <li><a href="team.html">Team</a></li>
                                    <li><a href="#">Tin tức</a></li>
                                    <li><a href="#">Login</a></li>
                                </ul>
                            </div>
                        </div>

                    </div>

                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="mb-5">
                            <h3 class="footer-heading mb-4">Video Namek</h3>

                            <div class="block-16">
                                <video width="100%" controls>
                                    <source src="/Assets/Client/images/Hành Tinh Namek.mp4" type="video/mp4">
                                </video>
                            </div>
                            
                        </div>

                    </div>

                </div>
            </div>
        </footer>
        <section class="footer-copy">
            <div class="container">
                <!-- Copyrights -->
                <div class="copyright">
                    © 2019 Namek. All Rights Reserved.
                </div>
            </div>
        </section>
    </div>
    
    <script src="/Assets/Client/js/jquery-3.3.1.min.js"></script>
    <script src="/Assets/Client/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="/Assets/Client/js/jquery-ui.js"></script>
    <script src="/Assets/Client/js/popper.min.js"></script>
    <script src="/Assets/Client/js/bootstrap.min.js"></script>
    <script src="/Assets/Client/js/owl.carousel.min.js"></script>
    <script src="/Assets/Client/js/jquery.stellar.min.js"></script>
    <script src="/Assets/Client/js/jquery.countdown.min.js"></script>
    <script src="/Assets/Client/js/jquery.magnific-popup.min.js"></script>
    <script src="/Assets/Client/js/aos.js"></script>

    <script src="/Assets/Client/js/main.js"></script>

</body>
</html>